cri-o/packaging

dependencies.yaml, scripts/helpers, scripts/obs
/kind cleanup
`krel obs stage` now waits per default, means we can avoid the additional flag.
None
None
```release-note
None
```
=> Update krel to v0.16.3

README.md, test/deb/Vagrantfile, test/rpm/Vagrantfile
Don't explicitly list the dependencies and repositories, but let the package manager sort it out. Only the wanted.
/kind cleanup
Improve vagrant
None
```release-note
None
```
-----
Here is `dnf`, sorting out the dependencies:
```
[   62.655610] cloud-init[973]: + dnf install -y cri-o kubelet kubeadm kubectl
[   68.056763] cloud-init[973]: CRI-O                                           422  B/s | 2.1 kB     00:05
[   74.584228] cloud-init[973]: Kubernetes                                      1.7 kB/s | 9.9 kB     00:05
[   75.653594] cloud-init[973]: Dependencies resolved.
[   75.668175] cloud-init[973]: ================================================================================
[   75.668302] cloud-init[973]:  Package                      Arch    Version                 Repository …
```
=> Make the two Vagrantfiles a little more similar

templates/latest/cri-o/cri-o.spec
/kind feature
This allows compatibility with the `golang-github-containers-image` package which writes `/etc/containers/registries.conf`. We now fallback to a CRI-O specific drop-in.
Follow-up on https://github.com/cri-o/packaging/issues/3
Ref https://github.com/cri-o/packaging/issues/3#issuecomment-1759713675
PTAL @afbjorklund
```release-note
Switched to registries.conf.d drop-in instead of main registries.conf to make the packages compatible with `golang-github-containers-image`.
```
=> Use registries.conf.d instead of main registries.conf

templates/latest/cri-o/cri-o.spec, test/rpm/Dockerfile
/kind cleanup
Removes unused dependency on "containernetworking-plugins":
`/usr/lib/cni`
Convert the (mandatory) requires "kubernetes-cni" into recommends:
`/opt/cni/bin`
None
The ubuntu packages were quite old anyway, so did not match the requirement:
https://packages.ubuntu.com/containernetworking-plugins
The kubelet for 1.28 requires CNI 1.2, and those packages only featured 1.1.1
Let the kubernetes repo deal with it, and leave it "optional"
```release-note
None
```
=> Remove dependency on containernetworking-plugins

.github/workflows/obs.yml, scripts/bundle/build, scripts/github-job-wait, scripts/obs, scripts/vars
/kind ci
Avoiding GitHub actions races by:
- Waiting for jobs running for the same CRI-O commit
- Re-using the variables across the jobs
None
None
```release-note
None
```
=> Reuse environment vars and wait for GitHub actions to avoid races

get, scripts/bundle/build, templates/latest/cri-o/bundle/install
/kind deprecation
The binary is already deprecated so we do not have to ship it in v1.28 and beyond.
None
Refers also to https://github.com/cri-o/cri-o/pull/7440
```release-note
Removed `crio-status` binary in favor of the `crio status` subcommand.
```
=> Remove `crio-status` binary

.github/workflows/obs.yml
We still need to run the release step, which got blocked by the deactivated `test-kubernetes` job.
None
None
```release-note
None
```
=> Run `release` step independent from test-kubernetes

scripts/reconcile
/kind ci
The script thinks the version already exists but we need a dedicated path for .0 releases.
None
None
```release-note
None
```
=> Fix v1.x.0 version reconcile logic in script

test/deb/Dockerfile, test/deb/Vagrantfile, test/deb/lima.yaml, test/rpm/Dockerfile, test/rpm/Vagrantfile, test/rpm/lima.yaml
/kind ci
The keys are not available when the project is recently created because of the CDN caching. We avoid that by using the fallback URL's.
None
None
```release-note
None
```
=> Don't use CDN's for repo keys

get, scripts/bundle/build, templates/latest/cri-o/bundle/10-crio.conf, templates/latest/cri-o/bundle/install, templates/latest/cri-o/cri-o.spec
/kind feature
We now ship our own policy.json to fix https://github.com/cri-o/packaging/issues/68
This should allow installing Podman and CRI-O simultaneously.
Fixes #68 
None
```release-note
None
```
=> Use custom policy.json

README.md, get
Allow `s390x` as possible arch for the `get` script.
Refers to https://github.com/cri-o/cri-o/pull/7821
/hold
for https://github.com/cri-o/cri-o/pull/7821 to be merged first.
```release-note
Added s390x architecture support to `get` script 
```
=> Add s390x architecture support to `get` script

.github/workflows/obs.yml, dependencies.yaml, scripts/bundle/build, scripts/obs, templates/latest/cri-o/bundle/versions
/kind ci
Adding support to build s390x packages.
None
Requires:
```release-note
Added support for `s390x` packages and bundles.
```
=> Add support for s390x

.github/workflows/obs.yml, scripts/bundle/test, test/deb/Vagrantfile, test/deb/lima.yaml, test/rpm/Vagrantfile, test/rpm/lima.yaml
/kind ci
We do not need `criu` any more as runtime dependency, which is now reflected in the tests. We also increase the `crictl run/rmp` timeouts to deflake the bundle test. 
None
None
```release-note
None
```
=> Remove `criu` dependency and increase test timeouts

scripts/reconcile
/kind bug
We only have to remove packages when we have less than the maximum amount of items. This patch fixes that logic.
None
None
```release-note
None
```
=> Fix package deletion for projects with less than max items

.github/PULL_REQUEST_TEMPLATE.md
We usually do no releases from this repo, means we can default to a `release-note-none`.
None
```release-note
None
```
=> Remove release note from PR template

scripts/github-job-wait
/kind ci
From time to time the job watch throws a 502 error:
```
failed to get jobs: HTTP 502: Server Error (https://api.github.com/repos/cri-o/packaging/actions/runs/8682352551/jobs?per_page=100)
```
We now retry up to three times to make the test suite robust.
As follow-up, I opened: https://github.com/cli/go-gh/issues/157
```release-note
None
```
=> Retry GitHub job watch

.github/workflows/schedule.yml
/kind ci
The tag reconciler in CRI-O runs on `0 0 * * *`, means we give the packages now +1hour for the new version to be available and then reconcile the packages.
None
None
```release-note
None
```
=> Build packages 1h after possible CRI-O releases

templates/latest/cri-o/bundle/10-crio.conf
/kind other
This PR fixes a small nuisance where the default `crun` runtime writes its status to `/run/runc`, which is the default `runtime_root` value.
Fixes #104 
None
```release-note
In the default configuration, the crun runtime will now store its state to /run/crun instead of /run/runc.
```
=> Explicitly set runtime_root in the default config

templates/latest/cri-o/cri-o.spec
/kind bug
Changing to `/etc/default` for debian based distributions.
Fixes https://github.com/cri-o/cri-o/issues/8315
```release-note
None
```
=> Change `/etc/sysconfig` to `/etc/default` for debian distributions

templates/latest/cri-o/cri-o.rpmlintrc, templates/latest/cri-o/cri-o.spec
/kind ci
We cannot use fillup in the RPMs, so we skip that lint. Kubernetes does the same.
None
None
```release-note
None
```
=> Add rpmlintrc to make RPM build

dependencies.yaml, scripts/helpers
/kind ci
This allows future krel versions to wait for the build results and report the correct error.
None
Ref: https://github.com/kubernetes/release/issues/3632, https://github.com/cri-o/packaging/pull/123
```release-note
None
```
=> Update krel to v0.17.1

README.md, dependencies.yaml
We should use the latest stable version to hint end users to the right stream.
Refers to https://github.com/cri-o/cri-o/issues/8353
None
```release-note
None
```
=> Use latest CRI-O stable as docs default

templates/latest/cri-o/cri-o.spec
/kind ci
The variable is invalid for our use case, so we have to manually set it.
None
None
```release-note
None
```
=> Manually set libexec dir because it's wrong for RPM builders

.github/workflows/obs.yml
/kind ci
This allows to directly identify the used branch on the obs workflow name rather than just `obs`.
None
None
```release-note
None
```
=> Add `run-name` for OBS workflow

README.md
/kind feature
Adding the new stream together with the CRI-O release branch for the upcoming v1.32 release.
None
None
```release-note
None
```
=> Add 1.32 pre-release stream

scripts/github-actions-setup
The vagrant package does not seem to be available any more, so we use them from HashiCorp.
None
None
```release-note
None
```
=> Make vagrant in CI available

README.md, scripts/reconcile, scripts/vars, test/deb/lima.yaml, test/rpm/lima.yaml, test/scripts/install-deb.sh, test/scripts/install-rpm.sh
Moving over to the new sub projects which have been manually created by myself.
Refers to https://github.com/kubernetes/k8s.io/issues/7710
None
```release-note
None
```
=> Switch to new OBS subprojects

README.md
The text mentioned a "dedicated umbrella SUBproject", but now it has been moved to a separate project (under "isv").
Also it is no longer obvious where to find "kubernetes", since it is no longer the parent of the subproject - add link.
Clarify the projects/subprojects in OBS
None
* #221 
```release-note
None
```
=> CRI-O is no longer a subproject of Kubernetes

.github/workflows/obs.yml, dependencies.yaml, scripts/bundle/build, scripts/helpers, scripts/oci-artifacts
/kind ci
We now use the GitHub registry `github.com/cri-o/bundle` to publish the created bundles as OCI artifacts.
None
Gave it a test run within this repository in https://github.com/cri-o/packaging/actions/runs/14614207404
The artifacts are available in: https://github.com/cri-o/packaging/pkgs/container/bundle
Example for `main`: https://explore.ggcr.dev/?image=ghcr.io/cri-o/bundle:main
(also referenced by the tag `v1.33.0-dev`, `23bec10a74342c4913d5e5abedc80dff98d673da` and `23bec10`)
```bash
cosign verify \
--certificate-identity https://github.com/cri-o/packaging/.github/workflows/obs.yml@refs/heads/oci-artifacts \
--certificate-oidc-issuer https://token.actions.githubusercontent.com \
ghcr.io/cri-o/bundle:main
…
oras pull --platform linux/amd64 ghcr.io/cri-o/bundle:main
…
oras …
```
=> Add support for publishing CRI-O as OCI artifacts

get
/kind bug
This PR fixes GIT_REF when tag is specified.
Verified locally.
```
❯ cat get | sudo bash -s -- -t v1.33.1
Welcome to the CRI-O install script!
Using version: v1.33.1
No architecture provided, using: amd64
Checking if all commands are available: curl jq tar
Found cosign, verifying signatures
Downloading cri-o.amd64.v1.33.1.tar.gz
Downloading cri-o.amd64.v1.33.1.tar.gz.sig
Downloading cri-o.amd64.v1.33.1.tar.gz.cert
Downloading cri-o.amd64.v1.33.1.tar.gz.spdx
Downloading cri-o.amd64.v1.33.1.tar.gz.spdx.sig
Downloading cri-o.amd64.v1.33.1.tar.gz.spdx.cert
Verifying blob cri-o.amd64.v1.33.1.tar.gz
Verified OK
Verifying blob cri-o.amd64.v1.33.1.tar.gz.spdx
Verified OK
/tmp/tmp.H3YuuLdNS1/cri-o /tmp/tmp.H3YuuLdNS1 /home/atokubi/cri-o/packaging
Installing CRI-O
+ DESTDIR=
+ …
```
=> fix verify command
