.github/workflows/obs.yml
.gitignore
README.md
scripts/test-kubernetes
test/deb/Vagrantfile
test/rpm/Vagrantfile

Remove unnecessary bits from the deb and rpm Vagrantfile.

Cleanup Vagrantfile's

---

README.md
dependencies.yaml

Updating the docs to match the latest standard.
None
None
```release-note
None
```

Rework docs

---

README.md
scripts/obs
scripts/vars
templates/latest/cri-o/cri-o.spec
templates/latest/metadata.yaml

/kind cleanup
Move the templates to this repo.
None
None
```release-note
None
```

Move templates to this repository

---

test/deb/Dockerfile
test/deb/Vagrantfile
test/rpm/Dockerfile
test/rpm/Vagrantfile

/kind ci
Using the native URLs to avoid CDN caching.
None
None
```release-note
None
```

Use native OBS URLs for package testing

---

scripts/helpers
scripts/obs
scripts/test-kubernetes

/kind ci
Retry the `vagrant up` for more robust testing.
None
None
```release-note
None
```

Retry `vagrant up`

---

.github/workflows/test.yml
Makefile
dependencies.yaml

/kind ci
Adding shfmt and shellcheck to CI
None
None
```release-note
None
```

Add shfmt and shellcheck to CI

---

dependencies.yaml
scripts/helpers
scripts/obs

/kind ci
Use the binary instead of the repo.
None
None
```release-note
None
```

Use binary release of `krel`

---

.github/workflows/obs.yml

/kind cleanup
Remove unused caches.
None
None
```release-note
None
```

Remove unused caches

---

dependencies.yaml
scripts/helpers
scripts/obs

/kind feature
Update krel to v0.16.2 and enable auto-wait
None
None
```release-note
None
```

Update krel to v0.16.2 and auto-wait

---

README.md

Adding the new blog post from k8s.io.
None
None
```release-note
None
```

Add new blog post

---

test/deb/lima.yaml
test/rpm/lima.yaml

/kind feature
Fixes #20
https://lima-vm.io has notes on how to install Lima
```release-note
add yaml templates for running test with lima
```

Add lima.yaml as an alternative to Vagrantfile

---

.github/workflows/obs.yml

/kind ci 
Avoid a warning in CI. 
None
None 
```release-note
None
```

Set process_gcloudignore: false

---

templates/latest/cri-o/cri-o.spec

/kind bug
Fixing the spec path.
None
None
```release-note
None
```

Fix systemd unit path

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

/kind feature
None
None
```release-note
None
```

Update crun to 1.10

---

.github/workflows/obs.yml
.github/workflows/test.yml
.gitignore
Makefile
dependencies.yaml
get
scripts/tree-status

/kind feature
Moving the get-script into this repository for easy CRI-O bundle retrieval.
Refers to https://github.com/cri-o/cri-o/issues/7380
None
```release-note
Moved get script into this repository
```

Move get script into this repository

---

.github/workflows/obs.yml

/kind ci
We now update the bundle marker for every release branch or tag and not only for `main`.
None
None
```release-note
None
```

Let bundle marker universally work

---

dependencies.yaml
test/rpm/Vagrantfile

/kind ci
Using the CentOS LTS release over Fedora 38.
Fixes https://github.com/cri-o/packaging/issues/18
None
```release-note
None
```

Use CentOS Stream 9 for Vagrant tests

---

README.md

The documentation is mostly inferred from cri-o/cri-o, but provides more context what the CI pipeline actually does.
None
None
```release-note
None
```

Add docs about static binary bundles

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

None
None
```release-note
None
```

Bump crun to v1.11

---

test/rpm/lima.yaml

/kind cleanup
Fixes #18
Follow-up from:
* #33
OS changes from:
https://github.com/lima-vm/lima/blob/master/examples/centos-stream-9.yaml
```release-note
None
```

Use CentOS Stream for rpm lima yaml

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

Updated crun to v1.11.1.
None
None
```release-note
Updated crun to v1.11.1.
```

Bump crun to v1.11.1

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

None
None
```release-note
Updated runc to v1.1.10.
```

Bump runc to v1.1.10

---

.github/workflows/obs.yml
scripts/helpers
test/rpm/Vagrantfile

/kind ci
Fixing the box URL to change the correct variable. It also fixes the broken retry bash script.
None
None
```release-note
None
```

Fix RPM box url

---

.github/workflows/obs.yml

Disable the tests until
https://github.com/actions/runner-images/issues/8730 gets resolved.
None
None
```release-note
None
```

Disable vagrant based tests for now

---

Makefile
dependencies.yaml

/kind ci
Update zeitgeist to the latest release.
None
None
```release-note
None
```

Update zeitgeist to v0.4.3

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

None
None
```release-note
None
```

Update crun to 1.11.2

---

dependencies.yaml
scripts/helpers

/kind ci
Update krel to the latest release.
None
None
```release-note
None
```

Update krel to v0.16.4

---

.github/workflows/obs.yml

https://github.com/actions/runner-images/issues/8730 seems to have resolved, so we now re-enable the tests.
None
None
```release-note
None
```

Re-enable Vagrant based tests

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

None
None
```release-note
None
```

Update crun to 1.12

---

.github/workflows/obs.yml
scripts/github-actions-setup
scripts/test-kubernetes
test/deb/Vagrantfile
test/deb/lima.yaml
test/rpm/Vagrantfile
test/rpm/lima.yaml

/kind ci
GitHub actions runners now support KVM, we can move away from mac os
now.
None
None
```release-note
None
```

Switch to Ubuntu based Vagrant tests

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

Update CNI plugins to the latest release.
None
None
```release-note
Updated cni-plugins to v1.4.0.
```

Update cni-plugins to v1.4.0

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

Update cri-tools to the latest release.
None
None
```release-note
Updated cri-tools to v1.29.0.
```

Update cri-tools to v1.29.0

---

README.md
dependencies.yaml
test/deb/Vagrantfile
test/deb/lima.yaml
test/rpm/Vagrantfile
test/rpm/lima.yaml

/kind ci
Update the test Kubernetes version to the latest minor tag.
None
None
```release-note
None
```

Update Kubernetes to v1.29.0

---

.github/workflows/obs.yml

The architecture has been forgotten to add to the publishing step which makes CI fail. This is now fixed.
None
None
```release-note
None
```

Publish ppc64le bundle too

---

.github/workflows/obs.yml
dependencies.yaml

/kind ci
Remove the exclude section by restructuring the input data.
None
None
```release-note
None
```

Simplify GitHub actions test matrix

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

Update conmon to the latest release.
None
None
```release-note
None
```

Update conmon to v2.1.9

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

None
None
```release-note
None
```

Update conmon to v2.1.10

---

get
scripts/bundle/build
templates/latest/cri-o/bundle/10-crun.conf
templates/latest/cri-o/bundle/install
templates/latest/cri-o/cri-o.spec

/kind feature
This allows shipping various versions of the binary and always using the right one for CRI-O.
Fixes https://github.com/cri-o/packaging/issues/67
PTAL @afbjorklund 
/hold
```release-note
None
```

Prefix crun, runc and conmon binaries with `crio-`

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

None
None
```release-note
None
```

Update crun to 1.14

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

None
None
```release-note
None
```

Update runc to 1.1.11

---

README.md

Adding the package streams for v1.30 releases.
None
None
```release-note
None
```

Add v1.30 package streams

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

Fixes CVE-2024-21626
None
None
```release-note
None
```

Update runc to 1.1.12

---

templates/latest/cri-o/cri-o.spec

/kind feature
We can now ship runc and conmon-rs in the same way as we do for the bundles.
None
None
```release-note
None
```

Ship `crio-runc` and `crio-conmonrs` as part of the packages

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

None
None
```release-note
None
```

Update crun to 1.14.1

---

dependencies.yaml
scripts/bundle/build
templates/latest/cri-o/bundle/versions

/kind ci
Bump CNI plugins to the latest release.
None
None
```release-note
None
```

Update cni-plugins to v1.4.1

---

dependencies.yaml
scripts/helpers

@cri-o/cri-o-maintainers PTAL
None
None
```release-note
None
```

Update krel to v0.16.6

---

test/deb/Vagrantfile
test/deb/lima.yaml
test/rpm/Vagrantfile
test/rpm/lima.yaml

/kind ci
Add `criu` since it's enabled per default now.
None
None
```release-note
None
```

Fix missing package in tests

---

.github/workflows/obs.yml

/kind ci
Ensure that all tests run through even if one fails.
cc @cri-o/cri-o-maintainers 
None
None
```release-note
None
```

Don't fail-fast test matrix suites

---

dependencies.yaml
scripts/helpers

Bump OSC to the latest release.
None
cc @cri-o/cri-o-maintainers 
```release-note
None
```

Update osc to v1.6.1

---

.github/workflows/obs.yml
.github/workflows/schedule.yml
.github/workflows/test.yml

/kind ci
Dependabot is able to update the version comments, means we can pin the actions to certain commits rather than branches.
None
None
```release-note
None
```

Pin GitHub actions commits

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

None
None
```release-note
None
```

Update conmon-rs to v0.6.3

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

Update conmon to the latest release.
None
None
```release-note
None
```

Update conmon to v2.1.11

---

.github/workflows/obs.yml

/kind ci
Enable s390x in tests.
None
None
```release-note
None
```

Enable s390x in tests

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

None
None
```release-note
None
```

Bump crun to v1.15

---

README.md

Adding the package streams for v1.31 releases.
None
None
```release-note
None
```

Add v1.31 package streams

---

scripts/bundle/build

cni-plugins removed their `LICENSE` and `README.md` from the existing release. We're now fixing the amount of files to make the CI pass again.
None
None
```release-note
None
```

Fix amount of files in bundle

---

dependencies.yaml
scripts/bundle/build
templates/latest/cri-o/bundle/versions

Update CNI plugins to the latest release.
None
None
```release-note
None
```

Update cni-plugins to v1.5.0

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

Update conmon to the latest release.
None
None
```release-note
None
```

Update conmon to v2.1.12

---

scripts/test-architectures
test/deb/Dockerfile
test/rpm/Dockerfile
test/scripts/install-deb.sh
test/scripts/install-rpm.sh
test/scripts/versions.sh

/kind ci
This PR is a follow-up to #112 . It:
- allows for `PROJECT_PATH` to be set externally in `versions.sh`;
- adds a `--crio-only` argument to `install-[deb|rpm].sh`, that when used, it only installs the `cri-o` package;
- updates the `Dockerfile`s to copy and run the `test/scripts` inside the build container;
- updates the `test-architectures` script to properly set the build `Dockerfile` and context.
None
None
```release-note
None
```

Refactor Docker integration tests

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

None
None
```release-note
None
```

Bump runc to v1.1.13

---

scripts/bundle/build
templates/latest/cri-o/bundle/install
templates/latest/cri-o/cri-o.spec

/kind feature
Adding the required files based on the original from the CRI-O repository.
None
Per https://github.com/cri-o/packaging/pull/118#discussion_r1652486257
```release-note
None
```

Add `/etc/{default,sysconfig}/crio` to bundle and spec

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

None
None
```release-note
None
```

Update CNI plugins to v1.5.1

---

templates/latest/cri-o/cri-o.spec

/kind ci
The packages complain that they're not included, so we have to add them.
None
None
```release-note
None
```

Add missing files to RPM/DEPs

---

.github/workflows/test.yml
dependencies.yaml
scripts/bundle/build

/kind ci
Update bom to the latest release.
None
None
```release-note
None
```

Update bom to v0.6.0

---

dependencies.yaml
scripts/helpers

/kind ci
This allows future krel versions to wait for the build results and report the correct error.
None
Ref: https://github.com/kubernetes/release/issues/3632, https://github.com/cri-o/packaging/pull/124
```release-note
None
```

Upgrade osc to 1.8.0

---

.github/workflows/test.yml
Makefile
README.md
dependencies.yaml

Add a toc to the readme to allow faster parsing.
None
None
```release-note
None
```

Add table of contents to README.md

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

Update cri-tools to v1.30.1
None
None
```release-note
None
```

Update cri-tools to v1.30.1

---

.github/workflows/obs.yml
dependencies.yaml
test/rpm/Dockerfile

/kind ci
Switch to Fedora 39 to fix the 404 in CI.
None
None
```release-note
None
```

Switch to Fedora 39 in CI

---

scripts/bundle/build
templates/latest/cri-o/bundle/10-crio.conf
templates/latest/cri-o/bundle/install
templates/latest/cri-o/cri-o.spec

/kind ci
Switching to `/usr/libexec/crio` instead of the `crio-*` binaries.
None
/hold
For testing.
```release-note
None
```

Switch to libexecdir

---

get

/kind cleanup
`get` script fixes as follow-up on https://github.com/cri-o/packaging/pull/131
None
None
```release-note
None
```

Update `get` script for libexec changes

---

dependencies.yaml
scripts/helpers

/kind ci
Update krel to the latest release.
None
None
```release-note
None
```

Update krel to v0.17.2

---

README.md
dependencies.yaml

Use the latest CRI-O minor version in the `get` script command for convenience.
None
None
```release-note
None
```

Use latest CRI-O version in `get` script docs

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

/kind ci
None
None
```release-note
None
```

Update conmon-rs to v0.6.4

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

None
None
```release-note
None
```

Update conmon-rs to v0.6.5

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

None
None
```release-note
None
```

crun: 1.15 -> 1.16

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

None
None
```release-note
None
```

Update cri-tools to v1.31.0

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

None
None
```release-note
None
```

Bump cri-tools to v1.31.1

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

None
None
```release-note
None
```

Update crun to 1.16.1

---

README.md
dependencies.yaml
test/deb/lima.yaml
test/rpm/lima.yaml
test/scripts/versions.sh

/kind ci
Test with the latest Kubernetes release.
None
None
```release-note
None
```

Test with Kubernetes v1.31.0

---

scripts/bundle/test

/kind ci
Verify that we actually have the right CRI-O version at hand.
None
None
```release-note
None
```

Verify correct git commit in bundle test

---

.github/dependabot.yml
.github/workflows/obs.yml
.github/workflows/schedule.yml
.github/workflows/test.yml
README.md
dependencies.yaml
test/deb/lima.yaml
test/rpm/lima.yaml

/kind cleanup
Run prettier on supported files and add a GitHub action to stay consistent.
None
None
```release-note
None
```

Run prettier on supported files

---

Makefile

/kind ci
This avoids issues when running on systems using SELinux.
None
None
```release-note
None
```

Make prettier target run in privileged container

---

dependencies.yaml
scripts/helpers
test/testdata/container.json

/kind ci
Update both to their latest release.
None
None
```release-note
None
```

Bump krel and debian-bookworm

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

None
None
```release-note
None
```

Update crun to 1.17

---

README.md
dependencies.yaml

Use CRI-O v1.31.0 as latest minor release reference.
None
None
```release-note
None
```

Reference latest CRI-O release

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

None
None
```release-note
None
```

Update conmon-rs to v0.6.6

---

dependencies.yaml
scripts/helpers

/kind ci
Update osc to the latest release.
None
None
```release-note
None
```

Update osc to v1.9.1

---

README.md

/kind ci
Preparing the 1.32 stable stream to be ready when the day comes.
None
None
```release-note
None
```

Add 1.32 stable stream

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

None
None
```release-note
None
```

Update runc to v1.1.15

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

/kind ci
Update CNI plugins to their latest release.
None
None
```release-note
None
```

Update cni-plugins to v1.6.0

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

/kind ci
Update runc and crun to their latest releases.
None
None
```release-note
None
```

Update runc to v1.2.0 and crun to 1.18

---

dependencies.yaml
scripts/helpers

/kind ci
None
None
```release-note
None
```

Update krel to v0.17.10

---

dependencies.yaml
scripts/helpers

/kind ci
None
None
```release-note
None
```

Update osc to v1.9.2

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

/kind ci
None
None
```release-note
None
```

Update crun to 1.18.2

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

None
None
```release-note
None
```

Update runc to v1.2.2

---

test/scripts/install-deb.sh
test/scripts/install-rpm.sh
test/scripts/test.sh

This should fix the failing CI tests.
None
None
```release-note
None
```

Disable IPv6 in CI

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

/kind ci
Bump the CNI plugins to the latest release.
None
None
```release-note
None
```

Update cni-plugins to v1.6.1

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

Update cri-tools to the latest release.
None
cc @cri-o/cri-o-maintainers 
```release-note
None
```

Bump cri-tools to v1.32.0

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

None
None
```release-note
None
```

Bump crun to v1.19

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

None
None
```release-note
None
```

Update runc to v1.2.3

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

None
None
```release-note
None
```

Update crun to 1.19.1

---

README.md

The february release was the last one for 1.29 and we can now mark it as EOL.
None
None
```release-note
None
```

Mark v1.29 as EOL

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

/kind cleanup
Use the latest crun.
None
None
```release-note
None
```

Update crun to 1.20

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

/kind ci
Updating runc to the latest release.
None
```release-note
None
```

Update runc to v1.2.5

---

README.md

There is no further content so replace the `:` with a `.`.
None
```release-note
None
```

Fix docs `:` vs `.`

---

dependencies.yaml
scripts/helpers

Update krel and pull the artifact directly from GitHub.
None
None
```release-note
None
```

Update krel to v0.18.0

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

Update conmon to the latest release.
None
None
```release-note
None
```

Update conmon to v2.1.13

---

dependencies.yaml
scripts/helpers

/kind ci
Update OSC to the latest release.
None
None
```release-note
None
```

Update osc to v1.13.0

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

/kind cleanup
None
None
```release-note
None
```

Update runc to v1.2.6

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

None
None
```release-note
None
```

Update crun to 1.21

---

dependencies.yaml
scripts/helpers

/kind ci
Update osc to the latest release.
None
```release-note
None
```

Update osc to v1.15.1

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

Update cri-tools to v1.33.0.
None
None
```release-note
None
```

Update cri-tools to v1.33.0

---

scripts/oci-artifacts

/kind ci
Use the default `latest` tag for CRI-O `main` branch commits.
None
None
```release-note
None
```

Use `latest` tag for `main` branch artifacts

---

scripts/oci-artifacts

/kind ci
Fixup the tags by using the actual branch and keep the information about the project.
None
None
```release-note
None
```

Use `REVISION` for branch

---

README.md

Adding some basic docs about how artifacts get published.
None
None
```release-note
None
```

Add docs for the OCI artifacts

---

.github/workflows/schedule.yml

/kind ci
Run the schedule workflow not for forks.
None
None
```release-note
None
```

Run `schedule` workflow not for forks

---

scripts/oci-artifacts

/kind cleanup
Streamline the annotations with respect to the other artifacts to indicate when the list has been created.
None
None
```release-note
None
```

Add `org.opencontainers.image.created` annotation to manifest list

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

/kind ci
Update CNI plugins to the latest release.
None
None
```release-note
None
```

Update cni-plugins to v1.7.1

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

/kind ci
Update the shipped runc version to the latest release.
None
None
```release-note
None
```

Update runc to v1.3.0

---

README.md

Reflect the latest changes to the artifacts by updating the docs:
- Adding more examples for tags
- Update the annotations.
None
None
```release-note
None
```

Update artifacts docs

---

dependencies.yaml
scripts/helpers

/kind ci
This PR fixes https://github.com/cri-o/packaging/actions/workflows/schedule.yml ci
It failed because of https://github.com/openSUSE/osc/issues/1819 .
The fix was verified here https://github.com/cri-o/packaging/actions/runs/15417498640 .
Fixes https://github.com/cri-o/cri-o/issues/9243
```release-note
None
```

Fix osc permission error.

---

README.md

Fixes the failing runs like: https://github.com/cri-o/packaging/actions/runs/15818510847/job/44582063195
@cri-o/cri-o-maintainers PTAL
None
```release-note
None
```

Fix prettier run in CI

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

Updated crun to 1.22.
https://github.com/containers/crun/releases/tag/1.22
Close https://github.com/cri-o/cri-o/issues/9251
```release-note
None
```

Update crun to 1.22

---

README.md

Mark the 1.30 release branches as EOL.
None
None
```release-note
None
```

Mark v1.30 as EOL

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

None
None
```release-note
None
```

Update conmon-rs to v0.7.0

---

README.md
get
templates/latest/cri-o/bundle/install

Add "uninstall" script to `get` file and add "uninstall" markdown to `README.md`
```release-note
None
```

Close issue #267

---

dependencies.yaml
test/rpm/Vagrantfile
test/rpm/lima.yaml

/kind ci
Use the centos 10 images for testing.
None
None
```release-note
None
```

Switch to centos 10

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

/kind ci
None
None
```release-note
None
```

Update conmon-rs to v0.7.2

---

dependencies.yaml
templates/latest/cri-o/bundle/versions

Update CNI plugins to the latest release.
None
None
```release-note
None
```

Update CNI plugins to v1.8.0

---

README.md
dependencies.yaml

Update the README to reflect the current release state.
None
@cri-o/cri-o-maintainers PTAL
```release-note
None
```

Add 1.35 projects and mark 1.34 as green

---

.github/workflows/test.yml
dependencies.yaml
scripts/helpers

/kind ci
Update bom to the latest release.
None
None
```release-note
None
```

Update bom to v0.7.1
